kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: iot-controller
  name: iot-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-controller
  template:
    metadata:
      labels:
        app: iot-controller
    spec:
      containers:
      - name: iot-controller
        image: fest/iot-controller
        imagePullPolicy: Always
        args:
          # No runtime arguments needed for in-cluster configuration.
          # Otherwise, it's a good place to put them.
          # - --apiserver=http://10.132.0.2:8080
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: iot-apiserver
  name: iot-apiserver
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-apiserver
  template:
    metadata:
      labels:
        app: iot-apiserver
    spec:
      containers:
      - name: iot-apiserver
        image: fest/iot-apiserver
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
          protocol: TCP
        args:
          # No runtime arguments needed for in-cluster configuration.
          # Otherwise, it's a good place to put them.
          # - --apiserver=http://10.132.0.2:8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: iot-apiserver
  name: iot-apiserver
  namespace: kube-system
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: iot-apiserver
  type: NodePort
